- id: deploy
  execute-command: "/app/webhook/watchtower-update.sh"
  command-working-directory: "/app"
  trigger-rule:
    match:
      type: "value"
      value: '{{ getenv "DEPLOY_SECRET" }}'
      parameter:
        source: "payload"
        name: "token"
