name: "another-tsp-bot"

services:
  fisa-bot:
    container_name: fisa-bot
    image: ghcr.io/fisa-telecom-sudparis/another-tsp-bot:master
    user: "1000:1000"
    build:
      context: .
      dockerfile: $PWD/Dockerfile
    env_file:
      - .env
    tty: true
    init: true
    restart: always
    volumes:
      - $PWD/data:/app/data
      - $PWD/config.toml:/app/config.toml
      - $PWD/external_data:/app/external_data
