services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "1000:1000"
    restart: always
    expose:
      - 8080
    volumes:
      - ./filebrowser_config/:/config/
    env_file:
      - .env
