name: CI

on:
  push:
  pull_request:

jobs:
  check:
    name: Execute test, check style, lint...
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
            version: 0.4.0
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
            python-version-file: "pyproject.toml"
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Execute pyright
        run: |
            uv run pyright src/
      - name: Execute ruff
        run: |
            uv run ruff format --check src/
            uv run ruff check

      # - name: Install tox
      #   run: |
      #     python -m pip install -U pip
      #     pip install tox
      # - name: Test application with tox
      #   run: |
      #     tox
      # - name: Upload test artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: pytest_results
      #     path: junit/test-results.xml
